require("sarthak.options")
require("sarthak.keymaps")

-- plugins
require("sarthak.plugins-config.plugins")
require("sarthak.colorschemes")
require("sarthak.cmp")
require("sarthak.lsp")
require("sarthak.telescope.telescope")
require("sarthak.treesitter")
require("sarthak.autopairs")
require("sarthak.comments")
require("sarthak.gitsigns")
require("sarthak.nvim-tree")
require("sarthak.bufferline")
require("sarthak.lualine.lualine-evil")
require("sarthak.toggleterm")
require("sarthak.indentline")
require("sarthak.alpha")
require("sarthak.impatient")
require("sarthak.vimnotify")
require("sarthak.neoclip")
require("sarthak.aeri")
require("sarthak.trouble")
require("sarthak.lf")
-- require("sarthak.wildmenu")
